export const data = [
  {
    _id: "62dcd8969958feea160de4f3",
    name: "O Fada do Dente",
    url: "https://cloclo60.cloud.mail.ru/weblink/view//hD8o/K2Q9GiTVi",
    image: "./image/TOOTHFAIRYWHORIZONTAL.jpeg",
    category: "romance",
    director: "Michael Lembeck",
    year: "2010",
    comments:
      "A hockey player breaks a little girl's heart when he tells her that there is no tooth fairy. Soon, he is summoned to the fairy world and punished to serve two weeks as a real-life tooth fairy.",
    createdAt: "2022-07-24T05:28:54.084Z",
    __v: 0,
  },
  {
    _id: "62dcd9439958feea160de4f5",
    name: "O Natal dos Coopers",
    url: "https://cloclo58.cloud.mail.ru/weblink/view//68jE/1rhzUuprK",
    image: "./image/Coopers.jpeg",
    category: "romance",
    director: "Jessie Nelson",
    year: "2015",
    comments:
      "The Coopers and their extended family are about to have the best Christmas Eve celebration ever until unexpected events and visitors turn it into a total mess.",
    createdAt: "2022-07-24T05:31:47.302Z",
    __v: 0,
  },
  {
    _id: "62dd6eff21e57fe7d158ffa3",
    name: "De Repente 30",
    url: "https://cloclo54.cloud.mail.ru/weblink/view//Wukh/ooJgbBPha",
    image: "./image/de-repente-30.jpeg",
    category: "romance",
    director: "Gary Winick",
    year: "2004",
    comments:
      "Jenna Rink makes an unusual wish on her birthday. Miraculously, her wish comes true and the 13-year-old Jenna wakes up the next day as a 30-year-old woman.",
    createdAt: "2022-07-24T16:10:39.365Z",
    __v: 0,
  },
  {
    _id: "62dd6fde21e57fe7d158ffa6",
    name: "The D.U.F.F",
    url: "https://cloclo13.cloud.mail.ru/weblink/view//H3K3/SogVCsj82",
    image: "./image/DUFF.jpeg",
    category: "comedia",
    director: "Ari Sandel",
    year: "2015",
    comments:
      "When Bianca realises that she is being used by people to get to her popular friends, she decides to change. She begs her former friend to rebuild her image in exchange for teaching him science.",
    createdAt: "2022-07-24T16:14:22.405Z",
    __v: 0,
  },
  {
    _id: "62dd712c21e57fe7d158ffa8",
    name: "Jumanji",
    url: "https://cloclo13.cloud.mail.ru/weblink/view//wKBy/sjWjPJmuu",
    image: "./image/jumanji-01.jpeg",
    category: "drama",
    director: "Joe Johnston",
    year: "1996",
    comments:
      "Two children come across a magical board game. While playing it, they meet Alan, a man who was trapped in the game, and attempt to free him while facing different kinds of danger.",
    createdAt: "2022-07-24T16:19:56.218Z",
    __v: 0,
  },
  {
    _id: "62dd71df21e57fe7d158ffaa",
    name: "Jumanji Bem Vindo A Selva",
    url: "https://cloclo14.cloud.mail.ru/weblink/view//mYyS/8uv97gxfm",
    image: "./image/jumanji-02.jpeg",
    category: "drama",
    director: "Jake Kasdan",
    year: "2018",
    comments:
      "When four students play with a magical video game, they are drawn to the jungle world of Jumanji, where they are trapped as their avatars. To return to the real world, they must finish the game.",
    createdAt: "2022-07-24T16:22:55.885Z",
    __v: 0,
  },
  {
    _id: "62dd726921e57fe7d158ffac",
    name: "Jumanji Próxima Fase",
    url: "https://cloclo51.cloud.mail.ru/weblink/view//pMYX/ianjaD5gd",
    image: "./image/jumanji-03.jpeg",
    category: "drama",
    director: "Jake Kasdan",
    year: "2019",
    comments:
      "When Spencer goes missing, the gang returns to Jumanji to travel unexplored territories and help their friend escape the world's most dangerous game.",
    createdAt: "2022-07-24T16:25:13.483Z",
    __v: 0,
  },
  {
    _id: "62dd72eb21e57fe7d158ffae",
    name: "Freaky Friday",
    url: "https://cloclo61.cloud.mail.ru/weblink/view//6jRa/SrqiLfpEk",
    image: "./image/Freaky-Friday.jpeg",
    category: "comedia",
    director: "Mark Waters",
    year: "2003",
    comments:
      "Tess and her daughter, Anna, do not get along. Things take a turn when, in a freak incident, their bodies are switched and they are forced to live each other's lives.",
    createdAt: "2022-07-24T16:27:23.985Z",
    __v: 0,
  },
  {
    _id: "62dd737f21e57fe7d158ffb1",
    name: "Click",
    url: "https://cloclo60.cloud.mail.ru/weblink/view//636s/hQLaJwzUD",
    image: "./image/click.jpeg",
    category: "comedia",
    director: "Frank Coraci",
    year: "2006",
    comments:
      "An architect discovers a universal remote that permits him to fast-forward and rewind to certain portions of his life. Complexities emerge when the remote begins to override his preferences.",
    createdAt: "2022-07-24T16:29:51.128Z",
    __v: 0,
  },
  {
    _id: "62dd73ee21e57fe7d158ffb3",
    name: "Dirty 30",
    url: "https://cloclo61.cloud.mail.ru/weblink/view//dyyd/XxWcXfFBh",
    image: "./image/Dirty30.jpeg",
    category: "comedia",
    director: "Andrew Bush",
    year: "2016",
    comments:
      "On the eve of a woman's 30th birthday, she agrees to let her two lifelong friends throw her a party. But what's supposed to be a simple celebration becomes a wild who's who of past and present, and things quickly spiral out of control.",
    createdAt: "2022-07-24T16:31:42.476Z",
    __v: 0,
  },
  {
    _id: "62dd747821e57fe7d158ffb5",
    name: "New York Minute",
    url: "https://cloclo60.cloud.mail.ru/weblink/view//qu4M/hGAED3Hcc",
    image: "./image/NewYorkMinute.jpeg",
    category: "drama",
    director: "Dennie Gordon",
    year: "2004",
    comments:
      "Two sisters who just can't get along have to travel to New York City. A series of mishaps compel the adversarial duo, in order to accomplish their goals, to unite against the forces around them.",
    createdAt: "2022-07-24T16:34:00.386Z",
    __v: 0,
  },
  {
    _id: "62dd751821e57fe7d158ffb7",
    name: "The Edge of Seventeen (No Limiar dos 18)",
    url: "https://cloclo52.cloud.mail.ru/weblink/view//DRgz/eGEFUGrc1",
    image: "./image/QUASE18.jpeg",
    category: "drama",
    director: "Kelly Fremon Craig",
    year: "2017",
    comments:
      "Nadine has problems with her mother and brother and considers her father as her only ally. However, things take a turn for worse for her when her best friend, Krista, starts dating her brother..",
    createdAt: "2022-07-24T16:36:40.634Z",
    __v: 0,
  },
  {
    _id: "62dd761b21e57fe7d158ffba",
    name: "Nowhere Boys: The Book of Shadows",
    url: "https://cloclo13.cloud.mail.ru/weblink/view//AEXv/zAQ7kDcVU",
    image: "./image/NowhereBoys.jpeg",
    category: "ficção",
    director: "David Caesar",
    year: "2016",
    comments:
      "When Felix finds a book that is magically sealed, he decides to get back together with the boys. They release Tegan, a powerful force that can help them.",
    createdAt: "2022-07-24T16:40:59.733Z",
    __v: 0,
  },
  {
    _id: "62dd772a21e57fe7d158ffbc",
    name: "Efeito Borboleta",
    url: "https://cloclo50.cloud.mail.ru/weblink/view//FtBV/3StKjvY1o",
    image: "./image/efeito-borboleta-1.jpeg",
    category: "ficção",
    director: "Eric Bress, J. Mackye Gruber",
    year: "2004",
    comments:
      "Evan gets severe headaches that cause him to suffer blackouts. While unconscious, he is able to travel back in time and alter the past but this causes drastic changes in his present life.",
    createdAt: "2022-07-24T16:45:30.204Z",
    __v: 0,
  },
  {
    _id: "62dd778321e57fe7d158ffbe",
    name: "Efeito Borboleta 2",
    url: "https://cloclo54.cloud.mail.ru/weblink/view//kdHx/tryK8Uqrr",
    image: "./image/efeito-borboleta-2.jpeg",
    category: "ficção",
    director: "Eric Bress, J. Mackye Gruber",
    year: "2006",
    comments:
      "After his girlfriend dies in a tragic accident, Nick Larson discovers that he has the ability to travel back in time and sets out to stop the incident from happening.",
    createdAt: "2022-07-24T16:46:59.759Z",
    __v: 0,
  },
  {
    _id: "62dd781021e57fe7d158ffc0",
    name: "Efeito Borboleta Revelação",
    url: "https://cloclo21.cloud.mail.ru/weblink/view//mwLd/FPbTPewvy",
    image: "./image/efeito-borboleta-3-revelacao.jpeg",
    category: "ficção",
    director: "Seth Grossman",
    year: "2009",
    comments:
      "When Sam Reide (Chris Carmack) goes back in time to save his sister, Jenna (Rachel Miner), from a house fire, he inadvertently creates an alternate history in which his parents die prematurely. In the wake of the mishap, the budding time traveler swears not to interfere with history again. But, when an innocent man ends up on death row for murdering his girlfriend, Reide ignores Jenna's warnings and prepares to leap one last time to witness the crime and bring the real killer to justice.",
    createdAt: "2022-07-24T16:49:20.386Z",
    __v: 0,
  },
  {
    _id: "62dd7a1121e57fe7d158ffc3",
    name: "The Space Between Us",
    url: "https://cloclo13.cloud.mail.ru/weblink/view//wKBy/sjWjPJmuu",
    image: "./image/space-between-us.jpeg",
    category: "romance",
    director: "Peter Chelsom",
    year: "2017",
    comments:
      "Sarah Elliot, an astronaut, dies on Mars while giving birth to her son. The boy visits Earth and starts searching for his father with the help of a clever girl.",
    createdAt: "2022-07-24T16:57:53.917Z",
    __v: 0,
  },
  {
    _id: "62dd7b4f21e57fe7d158ffc6",
    name: "O Plano imperfeito (Set it up)",
    url: "https://cloclo61.cloud.mail.ru/weblink/view//9MYo/fXQL4WnTY",
    image: "./image/o-plano-perfeito.jpeg",
    category: "romance",
    director: "Claire Scanlon",
    year: "2018",
    comments:
      "Two overworked and underpaid assistants come up with a plan to get their bosses off their backs by setting them up with each other.",
    createdAt: "2022-07-24T17:03:11.911Z",
    __v: 0,
  },
  {
    _id: "62dd84c821e57fe7d158ffcc",
    name: "This is 40",
    url: "https://cloclo58.cloud.mail.ru/weblink/view//zEne/cttpYe4YW",
    image: "./image/this-is-40.jpeg",
    category: "comedia",
    director: "Judd Apatow  ",
    year: "2013",
    comments:
      "Long-time married couple Pete and Debbie struggle with the idea of turning 40. With disobedient kids and rising debts coupled with an unwanted pregnancy, the two head towards a myriad of problems.",
    createdAt: "2022-07-24T17:43:36.220Z",
    __v: 0,
  },
  {
    _id: "62dd861c21e57fe7d158ffcf",
    name: "Coincidências do Amor",
    url: "https://cloclo13.cloud.mail.ru/weblink/view//WkgX/HDEBiQxmX",
    image: "./image/coincidencia-do-amor.jpeg",
    category: "comedia",
    director: "Josh Gordon",
    year: "2010",
    comments:
      "Kassie uses a sperm donor to conceive a child, much to the dismay of her best friend Wally. She remains in the dark for many years unaware that Wally replaced her sample with his own.",
    createdAt: "2022-07-24T17:49:16.992Z",
    __v: 0,
  },
  {
    _id: "62df13b18b7390cd1c691183",
    name: "Beauty Shop",
    url: "https://cloclo1.cloud.mail.ru/weblink/view//CpZM/7Agp3yAwN",
    image: "./image/BeautyShop.jpeg",
    category: "comedia",
    director: "Bille Woodruff",
    year: "2005",
    comments:
      "Gina works at a salon but her dream is to own a beauty shop. She quits her job and sets up her own business. It soon becomes the best place to get great haircuts and have heart-to-heart conversations.",
    createdAt: "2022-07-25T22:05:37.388Z",
    __v: 0,
  },
  {
    _id: "62df1c36f6d44412d237dfe5",
    name: "Desafiando Gigantes",
    url: "https://cloclo56.cloud.mail.ru/weblink/view//zE4T/gg3C1JwMC ",
    image: "./image/DesafiandoOsGigantes.jpeg",
    category: "drama",
    director: "Alex Kendrick",
    year: "2006",
    comments:
      "A coach, Grant Taylor, strives to inspire his disheartened football team to win despite the prospect of losing his job and facing a myriad of other problems.",
    createdAt: "2022-07-25T22:41:58.113Z",
    __v: 0,
  },
  {
    _id: "62df1dfef6d44412d237dfee",
    name: "Eu Sou a Lenda",
    url: "https://cloclo57.cloud.mail.ru/weblink/view//KeBT/uXTqPKrgu",
    image: "./image/EuSouALenda.jpeg",
    category: "ficção",
    director: "Francis Lawrence",
    year: "2008",
    comments:
      "Robert Neville, a scientist, is the last human survivor of a plague in the whole of New York. He attempts to find a way to reverse the effects of the man-made virus by using his own immune blood.",
    createdAt: "2022-07-25T22:49:34.380Z",
    __v: 0,
  },
  {
    _id: "62df1fc8f6d44412d237dff4",
    name: "Men in Black I",
    url: "https://cloclo55.cloud.mail.ru/weblink/view//7Xrg/PEcNSFoRx",
    image: "./image/HomensPreto.jpeg",
    category: "ficção",
    director: " Barry Sonnenfeld",
    year: "1997",
    comments:
      "K and J, (the men in black) are the scum-fighting super-agents; their latest mission is to save the world from a total intergalactic disaster.",
    createdAt: "2022-07-25T22:57:12.673Z",
    __v: 0,
  },
  {
    _id: "62df2026f6d44412d237dff6",
    name: "Men in Black II",
    url: "https://cloclo50.cloud.mail.ru/weblink/view//WCTh/Vuf7QJ7f5",
    image: "./image/HomensPreto2.jpeg",
    category: "ficção",
    director: " Barry Sonnenfeld",
    year: "2002",
    comments:
      "Agent J learns about Serleena, a shapeshifting alien, who is searching for the Light of Zartha on Earth. He seeks help from his now-retired former partner, Agent K, to find the Light before Serleena.",
    createdAt: "2022-07-25T22:58:46.159Z",
    __v: 0,
  },
  {
    _id: "62df2078f6d44412d237dff8",
    name: "Men in Black III",
    url: "https://cloclo50.cloud.mail.ru/weblink/view//4LA3/y4jjFabWr",
    image: "./image/HomensPreto3.jpeg",
    category: "ficção",
    director: " Barry Sonnenfeld",
    year: "2012",
    comments:
      "When Boris, an alien criminal, escapes a high-security prison, it is up to Agent J to bring him back. He goes back in time and finds a younger Agent K to help him in his quest.",
    createdAt: "2022-07-25T23:00:08.090Z",
    __v: 0,
  },
  {
    _id: "62df2158f6d44412d237dffc",
    name: "Homens de Preto 4",
    url: "https://cloclo51.cloud.mail.ru/weblink/view//esvq/vUVovH9BS",
    image: "./image/HomensPreto4.jpeg",
    category: "ficção",
    director: "F. Gary Gray",
    year: "2019",
    comments:
      "Agent M, a probationary member of the MIB, teams up with Agent H and uncovers a sinister plot that reveals a traitor in the organisation aiding an alien invasion.",
    createdAt: "2022-07-25T23:03:52.871Z",
    __v: 0,
  },
  {
    _id: "62df2433f6d44412d237e000",
    name: "Planeta dos Macacos",
    url: "https://cloclo61.cloud.mail.ru/weblink/view//kzo7/h4X7DfLtm",
    image: "./image/PlanetaMacacos.jpeg",
    category: "ficção",
    director: "Tim Burton",
    year: "2001",
    comments:
      "A space detour lands Leo, an astronaut, on a planet where talking apes rule over a planet of humans. He teams up with a rebel chimpanzee and a few humans in order to end the terror-ridden rule.",
    createdAt: "2022-07-25T23:16:03.408Z",
    __v: 0,
  },
  {
    _id: "62df2504f6d44412d237e002",
    name: "A Fuga do Planeta dos Macacos",
    url: "https://cloclo56.cloud.mail.ru/weblink/view//N566/YUWo9JsJB",
    image: "./image/AFugadoPlanetadosMacacos.jpeg",
    category: "ficção",
    director: "Don Taylor",
    year: "1971",
    comments: `In this second sequel to "Planet of the Apes," three apes flee their world before it's destroyed, and travel back in time to present-day America. When the humans discover that the trio are intelligent and capable of speech, they treat them as experimental research animals until they attempt to escape.`,
    createdAt: "2022-07-25T23:19:32.896Z",
    __v: 0,
  },
  {
    _id: "62df25e9f6d44412d237e005",
    name: "Antes de Partir",
    url: "https://cloclo61.cloud.mail.ru/weblink/view//SAZh/YdnobpdsF",
    image: "./image/AntesdePartir.jpeg",
    category: "drama",
    director: "Rob Reiner",
    year: "2007",
    comments:
      "Two terminally ill men left with only six months to live, decide to explore life and make a bucket list comprising all the things they have never tried before.",
    createdAt: "2022-07-25T23:23:21.182Z",
    __v: 0,
  },
  {
    _id: "62df26aff6d44412d237e007",
    name: "Uma Noite no Museu",
    url: "https://cloclo54.cloud.mail.ru/weblink/view//gdyw/uKN6abLXW",
    image: "./image/UmaNoitenoMuseu.jpeg",
    category: "comedia",
    director: "Milan Trenc",
    year: "2013",
    comments:
      "Night at the Museum is a mixed live action and computer-animated American media franchise of fantasy-comedy films based on the 1993 children's book The Night at the Museum by Milan Trenc, are directed by Shawn Levy and written by Robert Ben Garant and Thomas Lennon",
    createdAt: "2022-07-25T23:26:39.169Z",
    __v: 0,
  },
  {
    _id: "62df28a9f6d44412d237e00a",
    name: "O Dilema",
    url: "https://cloclo61.cloud.mail.ru/weblink/view//VBQW/khJRR32VB",
    image: "./image/ODilema.jpeg",
    category: "comedia",
    director: "Ron Howard",
    year: "2011",
    comments:
      "Business partners Ronny and Nick are best friends since high school. Things turn nasty between them when Ronny discovers about Nick's wife's affair.",
    createdAt: "2022-07-25T23:35:05.749Z",
    __v: 0,
  },
  {
    _id: "62df2d12f6d44412d237e011",
    name: "Toda Forma de Amor",
    url: "https://cloclo50.cloud.mail.ru/weblink/view//isRE/cG6LCaB4Z",
    image: "./image/todaformadeamor.jpeg",
    category: "romance",
    director: "Mike Mills",
    year: "2011",
    comments:
      "Oliver, a graphic designer, is attracted to a free-spirited and unpredictable Anna. Memories of his father encourage him to open himself up to the potential of a true and long-lasting relationship.",
    createdAt: "2022-07-25T23:53:54.201Z",
    __v: 0,
  },
  {
    _id: "62df4dc266599c7ebfedd278",
    name: "You Again",
    url: "https://cloclo54.cloud.mail.ru/weblink/view//QJEp/cf2ZcgcdS",
    image: "./image/YouAgain.jpeg",
    category: "romance",
    director: "Andy Fickman",
    year: "2010",
    comments:
      "Marni, a successful woman, is shocked to learn that her brother is marrying her school bully from the past. When she tries to expose her, things do not go as planned.",
    createdAt: "2022-07-26T02:13:22.126Z",
    __v: 0,
  },
  {
    _id: "62df4fb166599c7ebfedd27a",
    name: "The Core",
    url: "https://cloclo55.cloud.mail.ru/weblink/view//CNcf/KQWLv1NcJ",
    image: "./image/theCore.jpeg",
    category: "ficção",
    director: "Jon Amiel",
    year: "2003",
    comments:
      "When the Earth's inner core stops spinning, it causes the planet's electromagnetic field to rapidly deteriorate. The only way to save planet Earth is to set the core spinning again.",
    createdAt: "2022-07-26T02:21:37.978Z",
    __v: 0,
  },
  {
    _id: "62df586466599c7ebfedd283",
    name: "Everything everything",
    url: "https://cloclo56.cloud.mail.ru/weblink/view//E9CP/azGatHFVm",
    image: "./image/everything.jpeg",
    category: "romance",
    director: "Stella Meghie",
    year: "2017",
    comments:
      "Confinada em sua casa devido a uma doença, uma garota de 18 anos, inteligente e cheia de imaginação, se apaixona pelo adolescente que mora ao lado.",
    createdAt: "2022-07-26T02:58:44.269Z",
    __v: 0,
  },
  {
    _id: "62e00f1ec52c8928eb54389b",
    name: "O Zelador Animal",
    url: "https://cloclo13.cloud.mail.ru/weblink/view//iG2b/4sMrE5G5Q",
    image: "./image/OZeladorAnimal.jpeg",
    category: "comedia",
    director: "Frank Coraci",
    year: "2011",
    comments:
      "Griffin Keyes, a much-loved zookeeper, is about to resign. The animals do not wish to part ways with him and decide to let him in on their little secret that they can talk.",
    createdAt: "2022-07-26T15:58:22.898Z",
    __v: 0,
  },
  {
    _id: "62e01049c52c8928eb54389d",
    name: "Um Faz de Conta Que Acontece",
    url: "https://cloclo1.cloud.mail.ru/weblink/view//fPMu/zczVvBcfn",
    image: "./image/UmFazdeContaQueAcontece.jpeg",
    category: "comedia",
    director: "Adam Shankman",
    year: "2008",
    comments:
      "The ordinary lives of a hotel handyman and his niece and nephew take a magical turn when the handyman's grand bedtime stories begin to come true.",
    createdAt: "2022-07-26T16:03:21.677Z",
    __v: 0,
  },
  {
    _id: "62e016eff1bc6b6117e95c76",
    name: "Mega romantic",
    url: "https://cloclo50.cloud.mail.ru/weblink/view//5hRH/iZWFNCjS4",
    image: "./image/Megaromantic.jpeg",
    category: "romance",
    director: "Todd Strauss-Schulson",
    year: "2019",
    comments:
      "Cínica em relação ao amor e desprezada em seu trabalho de Nova York, a arquiteta Natalie não acredita em romances e finais felizes. Depois de sofrer um golpe na cabeça durante uma briga com um assaltante no metrô, Natalie acorda em um universo paralelo e se vê interpretando a protagonista de uma comédia romântica na vida real.",
    createdAt: "2022-07-26T16:31:43.155Z",
    __v: 0,
  },
  {
    _id: "62e018a1f1bc6b6117e95c79",
    name: "Uma baba quase perfeita",
    url: "https://cloclo61.cloud.mail.ru/weblink/view//bxf3/6yckEknKg",
    image: "./image/umababaquaseperfeita.jpeg",
    category: "comedia",
    director: "Chris Columbus",
    year: "1993",
    comments:
      "Preocupado por ter pouco acesso aos seus filhos, o divorciado Daniel Hillard (Robin Williams) elabora um plano. Com a ajuda de seu irmão criativo Frank (Harvey Fierstein), ele se veste como uma velha mulher britânica e convence sua ex-mulher, Miranda (Sally Field), para contratá-lo como babá. As crianças adoram a Sra. Doubtfire e com sua ajuda, Daniel se torna um pai melhor. Porém quando ambos Daniel e sua persona babá vão ao mesmo restaurante, a situação os deixa em apuros.",
    createdAt: "2022-07-26T16:38:57.605Z",
    __v: 0,
  },
  {
    _id: "62e01b36f1bc6b6117e95c8a",
    name: "O idiota do meu irmão",
    url: "https://cloclo51.cloud.mail.ru/weblink/view//9owV/N68vFx9UZ",
    image: "./image/oidiotadomeuirmao.jpeg",
    category: "comedia",
    director: "Jesse Peretz",
    year: "2011",
    comments:
      "Ned vivia feliz cultivando vegetais orgânicos com sua namorada, mas foi preso ao tentar vender maconha a um policial. Quando sai da prisão, é rejeitado pela namorada e procura abrigo na casa das irmãs, que ficam enlouquecidas com o jeito do irmão.",
    createdAt: "2022-07-26T16:49:58.403Z",
    __v: 0,
  },
  {
    _id: "62e01c91f1bc6b6117e95c9d",
    name: "Juntos Pelo Acaso",
    url: "https://cloclo53.cloud.mail.ru/weblink/view//EtC8/ibMW6koqt",
    image: "./image/JuntosPeloAcaso.jpeg",
    category: "romance",
    director: "Greg Berlanti",
    year: "2010",
    comments:
      "Holly Berenson e Eric Messer saem em um encontro arranjado pelos seus melhores amigos Peter e Alisson, mas acaba sendo um desastre. A única coisa que eles têm em comum é a paixão pela afilhada Sophie. Só que um acidente fatal deixa a menina órfã dos pais e a dupla é designada para cuidar da pequenina. Obrigados a permanecerem juntos para cuidar dela, eles enfrentam as dificuldades típicas de quem passa a ser pai e mãe de uma hora para outra e começam, aos poucos, a se entender melhor.",
    createdAt: "2022-07-26T16:55:45.079Z",
    __v: 0,
  },
  {
    _id: "62e01e18f1bc6b6117e95caa",
    name: "O Primeiro Amor",
    url: "https://cloclo61.cloud.mail.ru/weblink/view//uM3z/intLsuX4A",
    image: "./image/OPrimeiroAmor.jpeg",
    category: "romance",
    director: "Rob Reiner",
    year: "2010",
    comments:
      "Juli Baker cai imediatamente de amores pelo seu vizinho, Bryce Loski, quando se conhecem na segunda série. Bryce, no entanto, não sente o mesmo. Daquele dia em diante, ele se esforça para manter a ousada e imprevisível Juli afastada. Depois de seis anos, ela começa a sentir que estava errada sobre ele ser o amor de sua vida. Infelizmente, isso acontece ao mesmo tempo que Bryce começa a pensar que também estava errado sobre Juli.",
    createdAt: "2022-07-26T17:02:16.310Z",
    __v: 0,
  },
  {
    _id: "62e0239bf1bc6b6117e95cad",
    name: "Ele Não Está Tão a Fim de você ",
    url: "https://cloclo55.cloud.mail.ru/weblink/view//QBzE/P1WvqVSzc",
    image: "./image/elenaoestataoafimdevoce.jpeg",
    category: "romance",
    director: "Ken Kwapis",
    year: "2009",
    comments:
      "Um grupo de homens e mulheres de Baltimore navega pela emoção dos primeiros encontros e pelos problemas da vida de casado enquanto tentam interpretar os sinais enviados pelo sexo oposto, com a esperança de ser a exceção à regra.",
    createdAt: "2022-07-26T17:25:47.531Z",
    __v: 0,
  },
  {
    _id: "62e05a086728d7572dfdf92d",
    name: "Due Date",
    url: "https://cloclo51.cloud.mail.ru/weblink/view//HY4u/ehtmVjyH4",
    image: "./image/umpartodeviagem.jpeg",
    category: "comedia",
    director: "Todd Phillips",
    year: "2010",
    comments:
      "Peter Highman must reach Los Angeles to make it in time for his child's birth. However, he is forced to travel with Ethan, an aspiring actor, who frequently lands him in trouble.",
    createdAt: "2022-07-26T21:18:00.605Z",
    __v: 0,
  },
  {
    _id: "62e05d466728d7572dfdf92f",
    name: "Uma Ladra Sem Limites",
    url: "https://cloclo14.cloud.mail.ru/weblink/view//8q7Z/Cja9aUDGs",
    image: "./image/umaladrasemliimites.jpeg",
    category: "romance",
    director: "Seth Gordon",
    year: "2013",
    comments:
      "Um homem vai atrás da mulher que clonou sua identidade e acabou com seu crédito financiando um estilo de vida luxuoso, mas acaba aprendendo grandes lições de vida com a ladra.",
    createdAt: "2022-07-26T21:31:50.036Z",
    __v: 0,
  },
  {
    _id: "62e154fdcaa1a43d908cb85c",
    name: "Como Você Sabe ",
    url: "https://cloclo14.cloud.mail.ru/weblink/view//8hhk/KenTzJ7sN",
    image: "./image/comovocesabe.jpeg",
    category: "romance",
    director: "Hans Zimmer",
    year: "2011",
    comments:
      "A vida inteira de Lisa Jorgenson foi definida pelo softbol, mas aos 31 anos, ela é considerada velha demais para jogar e é cortada do time. Sem rumo e desorientada, ela começa a sair com Matty, um mulherengo encantador que joga beisebol profissional. Na mesma época, ela vai a um encontro às cegas com George, um homem de negócios em péssima situação por causa de fraude de ações. Presa em um triângulo amoroso, Lisa reflete sobre o significado do amor.",
    createdAt: "2022-07-27T15:08:45.588Z",
    __v: 0,
  },
  {
    _id: "62e1900acaa1a43d908cb8f1",
    name: "Ligeiramente Grávidos",
    url: "https://cloclo52.cloud.mail.ru/weblink/view//xas3/gCJC5imXd",
    image: "./image/ligeiramentegravidos.jpeg",
    category: "comedia",
    director: "Judd Apatow",
    year: "2007",
    comments:
      "A jornalista de sucesso Alison Scott encontra um grande obstáculo depois que uma noite amorosa com Ben, um rapaz irresponsável que ela conheceu em um bar, resulta em gravidez. Primeiro ela pensa em criar o filho sozinha, mas depois decide procurar Ben para contar sobre a novidade e dar a ele uma chance de ser um pai presente. No entanto, ele não tem certeza se está pronto para ser pai, e os dois se perguntam se seriam parceiros compatíveis.",
    createdAt: "2022-07-27T19:20:42.933Z",
    __v: 0,
  },
  {
    _id: "62e1921acaa1a43d908cb8f3",
    name: "idas e vindas do amor",
    url: "https://cloclo59.cloud.mail.ru/weblink/view//tqdH/De23Ba77q",
    image: "./image/idasevindasdoamor.jpeg",
    category: "romance",
    director: "Garry Marshall",
    year: "2007",
    comments:
      "Em uma série de histórias conectadas, vários moradores de Los Angeles passam por altos e baixos em apenas um dia. No decorrer desse dia, eles encaram primeiros encontros, longos relacionamentos, paqueras adolescentes e chamas antigas.",
    createdAt: "2022-07-27T19:29:30.541Z",
    __v: 0,
  },
  {
    _id: "62e6e7dd0873200ed14310be",
    name: "Férias Frustradas",
    url: "https://cloclo56.cloud.mail.ru/weblink/view//MH4B/y4x5PE38Z",
    image: "./image/feriasfrustadas.jpeg",
    category: "comedia",
    director: "John Francis Daley, Jonathan M. Goldstein",
    year: "2015",
    comments:
      "Seguindo os passos do pai e ansiando por uma ligação familiar, Rusty Griswold surpreende sua esposa e seus dois filhos com uma viagem que atravessa o país para o parque de diversões favorito da família, o Walley World.",
    createdAt: "2022-07-31T20:36:45.780Z",
    __v: 0,
  },
  {
    _id: "62e6e8d20873200ed14310c0",
    name: "Cartas para Julieta ",
    url: "https://cloclo56.cloud.mail.ru/weblink/view//WuV2/bje4MUJ68",
    image: "./image/CartasParaJulieta.jpeg",
    category: "romance",
    director: "Gary Winick",
    year: "2010",
    comments:
      "Em visita à cidade italiana de Verona com seu noivo ocupado, uma jovem chamada Sophie visita um muro onde os desiludidos deixam cartas para a trágica heroína de Shakespeare, Julieta Capuleto. Ao encontrar uma dessas cartas, de 1957, a jovem decide escrever à autora, Claire. Inspirada pela atitude de Sophie, Claire decide procurar por seu antigo amor.",
    createdAt: "2022-07-31T20:40:50.080Z",
    __v: 0,
  },
  {
    _id: "62e6e9c10873200ed14310c4",
    name: "Cartas para Deus",
    url: "https://cloclo11.cloud.mail.ru/weblink/view//CEkP/a4X2BFAiH",
    image: "./image/CartasParaDeus.jpeg",
    category: "drama",
    director: "David Nixon",
    year: "2010",
    comments:
      "Um menino de apenas oito anos de idade tem câncer e escreve suas orações em cartas para seu amigo Deus. Buscando um sentido para a vida, um carteiro encontra as orações do garoto e resolve ajudá-lo a mudar o destino de todos ao seu redor.",
    createdAt: "2022-07-31T20:44:49.566Z",
    __v: 0,
  },
  {
    _id: "62e6eaf70873200ed14310c6",
    name: "About Time",
    url: " https://cloclo50.cloud.mail.ru/weblink/view//Umjd/bK5UfiVDS",
    image: "./image/AboutTime.jpeg",
    category: "drama",
    director: "Richard Curtis",
    year: "2013",
    comments:
      "Depois de descobrir que ele pode viajar no tempo, o jovem Tim Lake usa sua habilidade para ganhar o coração da mulher dos seus sonhos e salvar seu amigo de um desastre profissional.",
    createdAt: "2022-07-31T20:49:59.688Z",
    __v: 0,
  },
  {
    _id: "62e6eb9c0873200ed14310c8",
    name: "As Loucuras de Dick & Jane",
    url: "https://cloclo51.cloud.mail.ru/weblink/view//2omb/kMu7wgw2h",
    image: "./image/AsLoucurasDeDickEJane.jpeg",
    category: "comedia",
    director: "Dean Parisot",
    year: "2005",
    comments:
      "O casal Dick e Jane vive de maneira confortável, mas ele acaba perdendo o emprego. Com o acúmulo de contas, a dupla decide roubar para pagar as dívidas e manter o estilo de vida, mas percebem que uma carreira criminosa pode ferir pessoas inocentes.",
    createdAt: "2022-07-31T20:52:44.893Z",
    __v: 0,
  },
  {
    _id: "62e6ebfe0873200ed14310ca",
    name: "Arrume um Emprego",
    url: " https://cloclo4.cloud.mail.ru/weblink/view//UZki/ypqsVZB9M",
    image: "./image/ArrumeUmEmprego.jpeg",
    category: "comedia",
    director: "Dylan Kidd",
    year: "2016",
    comments:
      "Após a faculdade, o casal Will e Jillian enfrenta as dificuldades do mercado de trabalho. Vivendo a realidade de expectativas não atendidas, eles se apoiam em suas famílias e amigos para lidar com o cotidiano.",
    createdAt: "2022-07-31T20:54:22.801Z",
    __v: 0,
  },
  {
    _id: "62e6ed3c0873200ed14310cc",
    name: "O Que Esperar Quando Você esta esperando ",
    url: "https://cloclo55.cloud.mail.ru/weblink/view//icdf/s2M3BhNiG",
    image: "./image/OQueEsperarQuandoVocêestaesperando .jpeg",
    category: "comedia",
    director: "Kirk Jones",
    year: "2012",
    comments:
      "Os desafios da paternidade iminente viram as vidas de cinco casais de cabeça para baixo. Duas celebridades se desesperam as demandas surpreendentes da gravidez. Hormônios causam estragos em um autora louca por bebês, enquanto seu marido tenta não ser superado por seu pai, que espera gêmeos com sua jovem esposa troféu. O marido de uma fotógrafa não tem certeza dos planos de adoção da esposa. Uma conexão única resulta em uma gravidez surpresa para os proprietários rivais de caminhões de alimentos.",
    createdAt: "2022-07-31T20:59:40.725Z",
    __v: 0,
  },
  {
    _id: "62e6edf10873200ed14310ce",
    name: "A Vida Acontece ",
    url: "https://cloclo53.cloud.mail.ru/weblink/view//RogH/txAtZtU1s",
    image: "./image/AVidaAcontece.jpeg",
    category: "romance",
    director: "Kat Coiro",
    year: "2012",
    comments:
      "Kim divide apartamento com duas amigas, mas a rotina da casa muda quando ela fica grávida. Agora, além de ter que descobrir como cuidar de uma criança, Kim também quer resolver sua vida amorosa.",
    createdAt: "2022-07-31T21:02:41.701Z",
    __v: 0,
  },
  {
    _id: "62e6eef50873200ed14310d0",
    name: "P.S. Eu Te Amo ",
    url: "https://cloclo59.cloud.mail.ru/weblink/view//uK9D/SJCpzEBtP",
    image: "./image/pseuteamo.jpeg",
    category: "romance",
    director: "Richard LaGravenese",
    year: "2008",
    comments:
      'Holly Kennedy é uma jovem bonita, feliz e realizada. Casou-se com o homem de sua vida, o apaixonado Gerry, que, infelizmente, fica doente e morre, deixando Holly em estado de choque. Antes de falecer, Gerry deixa para a esposa uma série de cartas. Mensagens sempre assinadas da mesma forma: "P.S. Eu te amo". A mãe e as amigas de Holly estão preocupadas porque as cartas mantêm a jovem presa ao passado. Entretanto, o fato é que as cartas estão ajudando a aliviar sua dor e guiá-la a uma nova vida.',
    createdAt: "2022-07-31T21:07:01.549Z",
    __v: 0,
  },
  {
    _id: "62e6efae0873200ed14310d4",
    name: "A Creche do Papai ",
    url: "https://cloclo61.cloud.mail.ru/weblink/view//iSTN/CJwvi68o6",
    image: "./image/ACrecheDoPapai.jpeg",
    category: "comedia",
    director: "Steve Carr",
    year: "2003",
    comments:
      "Enquanto sua esposa, Kim, sustenta a casa, o desempregado Charlie passa os dias cuidando do filho. Com a ajuda do amigo Phil, Charlie decide abrir uma creche. A ideia dá certo e logo contratam mais um empregado, Marvin. Charlie precisa lidar com a burocracia sem fim.",
    createdAt: "2022-07-31T21:10:06.663Z",
    __v: 0,
  },
  {
    _id: "62e6f0580873200ed14310d6",
    name: "Sex and city 2 ",
    url: "https://cloclo56.cloud.mail.ru/weblink/view//2sLT/8Q27eT6ao",
    image: "./image/SexAndCity2.jpeg",
    category: "romance",
    director: "Michael Patrick King",
    year: "2010",
    comments:
      "Diversão, moda e amizade continuam definindo as vidas de Carrie, Samantha, Charlotte e Miranda. As amigas passam férias em Abu Dhabi, onde terão muitas surpresas, especialmente Carrie, que, inesperadamente, encontrará Aidan.",
    createdAt: "2022-07-31T21:12:56.682Z",
    __v: 0,
  },
  {
    _id: "62e6f3360873200ed14310fd",
    name: "Viagem A Ilha Misteriosa 2",
    url: "https://cloclo52.cloud.mail.ru/weblink/view//2Xhy/1Gq3jjzzQ",
    image: "./image/viagemailhamisteriosa.jpeg",
    category: "drama",
    director: "Brad Peyton",
    year: "2012",
    comments:
      "Sean Anderson descobre uma misteriosa mensagem de rádio, que parece ter sido enviada por seu avô, desaparecido há dois anos. Ele não gosta de seu padrasto Hank Parsons, mas recebe sua ajuda para decifrar os códigos do texto, e juntos eles descobrem o paradeiro do idoso aventureiro em uma ilha misteriosa. Para chegar lá, a dupla contrata o piloto de helicóptero Gabato e sua filha Kailani, mas muitos perigos aguardam os viajantes na ilha.",
    createdAt: "2022-07-31T21:25:10.300Z",
    __v: 0,
  },
  {
    _id: "62e705460873200ed143114f",
    name: "A Série Divergente: Insurgente ",
    url: "https://cloclo21.cloud.mail.ru/weblink/view//SpSu/t6rHcQ7Db",
    image: "./image/insurgente.jpeg",
    category: "drama",
    director: "Robert Schwentke",
    year: "2015",
    comments:
      "Tris e Quatro agora são fugitivos perseguidos por Jeanine e os demais membros ambiciosos da Erudição, facção disposta a fazer tudo para capturá-los. O casal busca aliados e respostas nas ruínas da cidade de Chicago, tentando descobrir o que os familiares de Tris sacrificaram suas vidas para proteger. Tris aceita sua Divergência, mesmo sem saber exatamente o que pode perder ao fazê-lo. Em tempos de guerra, segredos emergem e as escolhas se tornam mais determinantes.",
    createdAt: "2022-07-31T22:42:14.471Z",
    __v: 0,
  },
  //add recentemente
  {
    _id: "62e705460873200ed143143r",
    name: "The Healer",
    url: "https://cloclo51.cloud.mail.ru/weblink/view//DQSG/JKPQdFEBy",
    image: "./image/TheHealer.jpeg",
    category: "drama",
    director: "Paco Arango",
    year: "2018",
    comments:
      "The Healer is a 2016 Spanish-Canadian-American comedy-drama film written and directed by Paco Arango and starring Oliver Jackson-Cohen, Camilla Luddington, Kaitlyn Bernard, Jorge Garcia and Jonathan Pryce. ",
    createdAt: "2022-07-31T22:42:14.471Z",
    __v: 0,
  },
  {
    _id: "62e705460873200ed143143fse",
    name: "Segurança de Shopping",
    url: "https://cloclo59.cloud.mail.ru/weblink/view//a4Rq/hUwWYKTCB",
    image: "./image/o-seguranca-do-shopping.jpeg",
    category: "comedia",
    director: "Steve Carr",
    year: "2009",
    comments:
      "Paul, a single dad who makes ends meet by working as a security guard at a mall, must save the day after thieves, dressed as Santa's employees, take over the mall.",
    createdAt: "2022-07-31T22:42:14.471Z",
    __v: 0,
  },
  {
    _id: "62e705460873200ed143143fsfw33",
    name: "Segurança de Shopping II",
    url: "https://cloclo57.cloud.mail.ru/weblink/view//96wH/MdjQCJxnB",
    image: "./image/seguranca-de-shopping-2.jpeg",
    category: "comedia",
    director: "Andy Fickman",
    year: "2015",
    comments:
      "Paul Blart, a security guard who saved a mall from criminals, earns a trip to Las Vegas. While on the vacation, Paul learns that the hotel he is staying at is in danger and steps up to save the day.",
    createdAt: "2022-07-31T22:42:14.471Z",
    __v: 0,
  },
  {
    _id: "62e705460873200ed143143fs342lj",
    name: "Não Sei Como Ela Consegue",
    url: "https://cloclo59.cloud.mail.ru/weblink/view//bHka/mZztX5B65",
    image: "./image/nao-sei-como-ela-consegue.jpeg",
    category: "romance",
    director: "Douglas McGrath",
    year: "2011",
    comments:
      "Kate Reddy, a banking professional, constantly struggles to manage her work and family. When a friend offers her a better job, she is torn between settling for a better wage and her children.",
    createdAt: "2022-07-31T22:42:14.471Z",
    __v: 0,
  },
  {
    _id: "62e705460873200fs4d143143fs342lj",
    name: "Salt",
    url: "https://cloclo1.cloud.mail.ru/weblink/view//SWyw/FjG4wLU2D",
    image: "./image/salt.jpeg",
    category: "ficção",
    director: "Phillip Noyce",
    year: "2010",
    comments:
      "CIA agent Evelyn Salt's life takes an ugly turn when she is accused of planning the assassination of the Russian president. However, she flees and sets out to prove her innocence.",
    createdAt: "2022-07-31T22:42:14.471Z",
    __v: 0,
  },
  {
    _id: "62e7fdsesdf60873200ed143143fs3342lj",
    name: "Legalmente Loira",
    url: "https://cloclo50.cloud.mail.ru/weblink/view//dZC7/f3vfJ7d4g",
    image: "./image/legalmente-loira.jpeg",
    category: "romance",
    director: "Robert Luketic",
    year: "2001",
    comments:
      "Elle's boyfriend breaks up with her for a smarter girl as he plans to become a politician and joins Harward law school. Elle gets enrolled in the same school in an effort to teach him a lesson.",
    createdAt: "2022-07-31T22:42:14.471Z",
    __v: 0,
  },
  {
    _id: "62e7fdsesdf6054300ed143143fs3342lj",
    name: "Race to Witch Mountain ",
    url: "https://cloclo21.cloud.mail.ru/weblink/view//zXDD/DU4zPC7b1",
    image: "./image/AMontanhaEnfeitiçada.jpeg",
    category: "ficção",
    director: "Andy Fickman",
    year: "2009",
    comments:
      "Jack, a taxi driver, finds himself helping two aliens who appear to look like human children and claim that they trying to save Earth and themselves from Siphon, a dangerous killer from outer space.",
    createdAt: "2022-07-31T22:42:14.471Z",
    __v: 0,
  },
];





 



